name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: win

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install Dependencies
      run: npm ci
      
    - name: Build for ${{ matrix.platform }}
      run: npm run build:${{ matrix.platform }}
      
    - name: Generate Changelog
      run: npx git-cliff --output CHANGELOG.md
      if: matrix.os == 'ubuntu-latest'
      
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: matrix.os == 'ubuntu-latest'
      with:
        body_path: CHANGELOG.md
        files: |
          dist/**/*.exe
          dist/**/*.deb
          dist/**/*.AppImage
          dist/**/*.zip
          dist/**/*.yml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}